package roteador.core.constants;


public enum ContextKey {
	

	CONTEXT("CONTEXT"),
    COMMAND_EXCEPTION("COMMAND_EXCEPTION"),
    SERVICE_EXCEPTION("SERVICE_EXCEPTION"),
    EXCEPTION("EXCEPTION"),
    TRANSACTION("TRANSACTION"),
    TRANSACTION_UUID("TRANSACTION_UUID"),
    APPLICATION_PATH("APPLICATION_PATH"),
    RESPONSE("RESPONSE"),
    REQUEST_JSON("REQUEST_JSON"),

   
    
    USER_TO("USER_TO"),
    API_LIST("API_LIST"),
    API_VERSION_LIST("API_VERSION_LIST"),
    API_DTO("API_DTO"),
    API_ID("API_ID"),
    API_VERSION("API_VERSION"),
    MEMBRO_ORGANIZACAO("MEMBRO_ORGANIZACAO"),
    DOCUMENTATION_VERSION("DOCUMENTATION_VERSION"),
    EMAIL("EMAIL"),
    JSON_PARSE_FROM_OBJECT("JSON_PARSE_FROM_OBJECT"),
    RETURN("RETURN"),
    RETURN_BODY_OBJECT("RETURN_BODY_OBJECT"),
    JSON_OBJECT("JSON_OBJECT"),
    MESSAGE("MESSAGE"),
    API_VERSION_STATUS_LIST("API_VERSION_STATUS_LIST")
    ;

    private String chave;

    private ContextKey(final String chave) {
        this.chave = chave;
    }

    public String getChave() {
    	return chave;
    }

}

