package roteador.core.constants;


public enum ECatalogueIntegration
{
	// Interactions
	INTERACTION_CREATE_DATE,
	INTERACTION_DELIVERYCHANNELCODE,
	INTERACTION_TOTAL_PRICE,
	INTERACTION_CURRENCY,
	INTERACTION_TYPE,
	
	INTERACTION_REQUEST_FROM,
	INTERACTION_REQUEST_TO,
	INTERACTION_REQUEST_LENGTH,
	INTERACTION_REQUEST_TYPE,
	INTERACTION_REQUEST_TYPE_ALL,
	INTERACTION_REQUEST_TYPE_EARN,
	INTERACTION_REQUEST_TYPE_REDEEM,
	
	// Basket
	BASKET_MEMBER_ORDER_ITEM_ID,
	
	// Balance
	CURRENCY_NAME,
	CURRENCY_AMOUNT,
	
	// Member
	MEMBER_ID,
	MEMBER_PROGRAM_CODE,
	MEMBER_DATE_BIRTH,
	MEMBER_DATE_CREATE,
	MEMBER_SALUTATION,
	MEMBER_NAME_FIRST,
	MEMBER_NAME_LAST,
	MEMBER_NAME_MIDDLE,
	MEMBER_GENDER,
	MEMBER_STATUS,
	MEMBER_LANGUAGE,

	// Address
	ADDRESS_PHYSICAL,
	ADDRESS_EMAIL,
	ADDRESS_DELIVERY,
	ADDRESS_CHARGING,
	ADDRESS_MOBILE,
	ADDRESS_SOCIAL,
	ADDRESS_INSTANT_MESSAGE,
	ADDRESS_PHONE;

}