package roteador.core.constants;


public enum ECatalogueContextKey {
	

	CONTEXT("CONTEXT"),
    COMMAND_EXCEPTION("COMMAND_EXCEPTION"),
    SERVICE_EXCEPTION("SERVICE_EXCEPTION"),
    EXCEPTION("EXCEPTION"),
    TRANSACTION("TRANSACTION"),
    TRANSACTION_UUID("TRANSACTION_UUID"),
    APPLICATION_PATH("APPLICATION_PATH"),
    RESPONSE("RESPONSE"),
    REQUEST_JSON("REQUEST_JSON"),
    ACCESS_VALIDATE_RESPONSE("ACCESS_VALIDATE_RESPONSE"),
    ACTIVE("ACTIVE"),
    SUPPLIER_KEY("SUPPLIER_KEY"),
    SUPPLIER_TO("SUPPLIER_TO"),
    SUPPLIER_TO_LIST("SUPPLIER_TO_LIST"),
    SUPPLIER_RESPONSE("SUPPLIER_RESPONSE"),
    SUPPLIER_CONTACT_TO("SUPPLIER_CONTACT_TO"),
    SUPPLIER_CONTACT_LIST_TO("SUPPLIER_CONTACT_LIST_TO"),
    SUPPLIER_CONTACT_ATTRIBUTE_TO("SUPPLIER_CONTACT_ATTRIBUTE_TO"),
    SUPPLIER_CONTACT_ATTRIBUTE_LIST_TO("SUPPLIER_CONTACT_ATTRIBUTE_LIST_TO"),
    SUPPLIER_CATEGORY_KEY("SUPPLIER_CATEGORY_KEY"),
    SEARCH_PRODUCT_PARAMS("SEARCH_PRODUCT_PARAMS"),
	
    CLIENT_KEY("CLIENT_KEY"),
    CLIENT_TO("CLIENT_TO"),
    CLIENT_TO_LIST("CLIENT_TO_LIST"),
    CLIENT_RESPONSE("CLIENT_RESPONSE"),    
    CLIENT_CONTACT_TO("CLIENT_CONTACT_TO"),
    CLIENT_CONTACT_LIST_TO(" CLIENT_CONTACT_LIST_TO"),
    CLIENT_CONTACT_ATTRIBUTE_TO("CLIENT_CONTACT_ATTRIBUTE_TO"), 
    CLIENT_CONTACT_ATTRIBUTE_LIST_TO("CLIENT_CONTACT_ATTRIBUTE_LIST_TO"),
    LOYALTY_ENGINE_CONNECTOR_LIST_TO("LOYALTY_ENGINE_CONNECTOR_LIST_TO"),
    LOYALTY_ENGINE_CONNECTOR_TO("LOYALTY_ENGINE_CONNECTOR_TO"),
   
    
    USER_TO("USER_TO"),
    USER_LIST_TO("USER_LIST_TO"),
    USER_PASSWORD("USER_PASSWORD"),
    USER_USERNAME("USER_USERNAME"),
    USER_KEY("USER_KEY"),
    ROLE_KEY("ROLE_KEY"),
    ACCESS_RULE_TO_LIST("ACCESS_RULE_TO_LIST"),
    MODULE_ACCESS_RULE_MAP("MODULE_ACCESS_RULE_MAP"),
    
    PROFILE_KEY("PROFILE_KEY"),
    PROFILE_TO("PROFILE_TO"),
    PROFILE_LIST_TO("PROFILE_LIST_TO"),
    
    SEGMENT_KEY("SEGMENT_KEY"),
    SEGMENT_TO("SEGMENT_TO"),
    SEGMENT_TO_LIST("SEGMENT_TO_LIST"),
    
    DEPARTMENT_KEY("DEPARTMENT_KEY"),
    DEPARTMENT_TO("DEPARTMENT_TO"),
    DEPARTMENT_TO_LIST("DEPARTMENT_TO_LIST"),
    
    PROGRAM_KEY("PROGRAM_KEY"),
    PROGRAM_TO("PROGRAM_TO"),
    PROGRAM_TO_LIST("PROGRAM_TO_LIST"),
    PROGRAM_RESPONSE("PROGRAM_RESPONSE"),
    PROGRAM_PRODUCTS_TO_LIST("PROGRAM_PRODUCTS_TO_LIST"),
    
    PROGRAM_CROSS_SELL_TO("PROGRAM_CROSS_SELL_TO"),
    PROGRAM_CROSS_SELL_KEY("PROGRAM_CROSS_SELL_KEY"),
    PROGRAM_CROSS_SELL_TO_LIST("PROGRAM_CROSS_SELL_TO_LIST"),
    LIST_PRIORITY_CROSS_SELL("LIST_PRIORITY_CROSS_SELL"),
    PROGRAM_CROSS_SELL_LOG_TO("PROGRAM_CROSS_SELL_LOG_TO"),
    PROGRAM_CROSS_SELL_LOG_TO_LIST("PROGRAM_CROSS_SELL_LOG_TO_LIST"),
    
    PROGRAM_STATIC_PAGE_KEY("PROGRAM_STATIC_PAGE_KEY"),
    
    PROGRAM_UI_PROPERTY_TO("PROGRAM_UI_PROPERTY_TO"),
    PROGRAM_UI_PROPERTY_TO_LIST("PROGRAM_UI_PROPERTY_KEY"),
    PROGRAM_UI_PROPERTY_KEY("PROGRAM_UI_PROPERTY_KEY"),
    
    STATIC_PAGE_KEY("STATIC_PAGE_KEY"),
    STATIC_PAGE_TO_LIST("STATIC_PAGE_TO_LIST"),
    STATIC_PAGE_TO("STATIC_PAGE_TO"),
    STATIC_PAGE_LOG_TO("STATIC_PAGE_LOG_TO"),
    STATIC_PAGE_LOG_TO_LIST("STATIC_PAGE_LOG_TO_LIST"),
    STATIC_PAGE_INITIAL_DATE("STATIC_PAGE_INITIAL_DATE"),
    STATIC_PAGE_EXPIRATION_DATE("STATIC_PAGE_EXPIRATION_DATE"),

    CATALOG_KEY("CATALOG_KEY"),
    CATALOG_TO("CATALOG_TO"),
    CATALOG_TO_LIST("CATALOG_TO_LIST"),
    CATALOG_RESPONSE("CATALOG_RESPONSE"),
    
    CATALOG_TENANT_ID("CATALOG_TENANT_ID"),
    
    REDEMPTION_CHANNEL_KEY("REDEMPTION_CHANNEL_KEY"),
    REDEMPTION_CHANNEL_TO("REDEMPTION_CHANNEL_TO"),
    REDEMPTION_CHANNEL_TO_LIST("REDEMPTION_CHANNEL_TO_LIST"),
    REDEMPTION_CHANNEL_RESPONSE("REDEMPTION_CHANNEL_RESPONSE"),
    
    PRICING_OFFER_KEY("PRICING_OFFER_KEY"),
    PRICING_OFFER_TO("PRICING_OFFER_TO"),
    PRICING_OFFER_TO_LIST("PRICING_OFFER_TO_LIST"),
    PRICING_OFFER_RESPONSE("PRICING_OFFER_RESPONSE"),

    PRICING_RULE_KEY("PRICING_RULE_KEY"),
    PRICING_RULE_TO("PRICING_RULE_TO"),
    PRICING_RULE_TO_LIST("PRICING_RULE_TO_LIST"),
    PRICING_RULE_RESPONSE("PRICING_RULE_RESPONSE"),
    PRICING_PRODUCT_VALUE_ADJUST_FACTOR_KEY("PRICING_PRODUCT_VALUE_ADJUST_FACTOR_KEY"),
    PRICING_PRODUCT_VALUE_ADJUST_FACTOR_TO("PRICING_PRODUCT_VALUE_ADJUST_FACTOR_TO"),
    PRICING_PRODUCT_VALUE_ADJUST_FACTOR_LIST("PRICING_PRODUCT_VALUE_ADJUST_FACTOR_LIST"),
    PRICING_PRODUCT_VALUE_ADJUST_FACTOR_LOG_LIST("PRICING_PRODUCT_VALUE_ADJUST_FACTOR_LOG_LIST"),
    PRICING_PRODUCT_VALUE_ADJUST_FACTOR_INITIAL_DATE("PRICING_PRODUCT_VALUE_ADJUST_FACTOR_INITIAL_DATE"),
    PRICING_PRODUCT_VALUE_ADJUST_FACTOR_EXPIRATION_DATE("PRICING_PRODUCT_VALUE_ADJUST_FACTOR_EXPIRATION_DATE"),
    PRICING_PRODUCT_VALUE_ADJUST_FACTOR_PRIORITY("PRICING_PRODUCT_VALUE_ADJUST_FACTOR_PRIORITY"),
    
    PROMOTION_TO("PROMOTION_TO"),
    PROMOTION_RULE_TO("PROMOTION_RULE_TO"),
    PROMOTION_ID("PROMOTION_ID"),
    PROMOTION_LIST("PROMOTION_LIST"),
    PROMOTION_DURATION_FROM("PROMOTION_DURATION_FROM"),
    PROMOTION_DURATION_TO("PROMOTION_DURATION_TO"),
    PROMOTION_LOG_LIST("PROMOTION_LOG_LIST"),
    PROMOTION_LIST_MEMBER("PROMOTION_LIST_MEMBER"),
    LIST_PRIORITY_PROMOTION("LIST_PRIORITY_PROMOTION"),
    DISCOUNT_TO("DISCOUNT_TO"),

    PRODUCT_TO("PRODUCT_TO"),
    PRODUCT_KEY("PRODUCT_KEY"),
    NEW_PRODUCT("NEW_PRODUCT"),
    PRODUCT_TO_LIST("PRODUCT_TO_LIST"),
    PRODUCT_STATUS("PRODUCT_TO"),
    PRODUCT_PUBLISH("PRODUCT_PUBLISH"),
    EXISTING_PRODUCT_TO_LIST("EXISTING_PRODUCT_TO_LIST"),
    NEW_PRODUCT_TO_LIST("NEW_PRODUCT_TO_LIST"),
    PRODUCT_FORM_TO("PRODUCT_FORM_TO"),
    PRODUCTS_IMAGES("PRODUCTS_IMAGES"),
    
    SUPPLIER_IMPORT_SCHEDULER_TO("SUPPLIER_IMPORT_SCHEDULER_TO"),
    SUPPLIER_IMPORT_SCHEDULER_KEY("SUPPLIER_IMPORT_SCHEDULER_KEY"),
    SCHEDULER_TO_LIST("SCHEDULER_TO_LIST"),
    SCHEDULER_TO("SCHEDULER_TO"),
    SCHEDULER_LOG_TO("SCHEDULER_LOG_TO"),
    SCHEDULER_LOG_TO_LIST("SCHEDULER_LOG_TO_LIST"),
    SKU_TO("SKU_TO"),
    SKU_TO_LIST("SKU_TO_LIST"),
    EXISTING_SKU_TO_LIST("EXISTING_SKU_TO_LIST"),
    NEW_SKU_TO_LIST("NEW_SKU_TO_LIST"), 
    
    CATEGORY_KEY("CATEGORY_KEY"), 
    CATEGORY_TO("CATEGORY_TO"), 
    CATEGORY_RESPONSE("CATEGORY_RESPONSE"), 
    CATEGORY_TO_LIST("CATEGORY_TO_LIST"),
    CATEGORY_CHILD("CATEGORY_CHILD"),
    CATEGORY_FRIENDLY_NAME("CATEGORY_FRIENDLY_NAME"),

    ORDER_TO("ORDER_TO"),
    ORDER_KEY("ORDER_KEY"),
    ORDER_TO_LIST("ORDER_TO_LIST"),
    ORDER_DATE_FROM("ORDER_DATE_FROM"),
    ORDER_DATE_TO("ORDER_DATE_TO"),
    ORDER_ITEM_TRACKING_TO_LIST("ORDER_ITEM_TRACKING_TO_LIST"),
    ORDER_ITEM_PAYMENT_METHOD_LIST("ORDER_ITEM_PAYMENT_METHOD_LIST"),
    ORDER_ITEM_PRODUCT_MAP("ORDER_ITEM_PRODUCT_MAP"),

    ORDER_ITEM_KEY("ORDER_ITEM_KEY"),
    ORDER_ITEM_TO("ORDER_ITEM_TO"),
    ORDER_ITEMS_TO_BE_MOVED("ORDER_ITEMS_TO_BE_MOVED"),
    ORDER_ITEM_TO_LIST("ORDER_ITEM_TO_LIST"),
    ORDER_ITEM_SUPPLIER_MAP("ORDER_ITEM_SUPPLIER_MAP"),
    ORDER_ITEMS_NOT_PROCESSED("ORDER_ITEMS_NOT_PROCESSED"),
    
    AUTOCOMPLETE_SEARCH_PROGRAM("AUTOCOMPLETE_SEARCH_PROGRAM"),
    AUTOCOMPLETE_SEARCH("AUTOCOMPLETE_SEARCH"),
    AUTOCOMPLETE_LIST("AUTOCOMPLETE_LIST"),
    
    CART_ITENS_QUANTITY("cartItensQuantity"),
    
    WISHLIST_TO("WISHLIST_TO"),
    WISHLIST_KEY("WISHLIST_KEY"),
    WISHLIST_TO_LIST("WISHLIST_TO_LIST"),
    WISHLIST_DATE_FROM("WISHLIST_DATE_FROM"),
    WISHLIST_DATE_TO("WISHLIST_DATE_TO"),
    WISHLIST_ITEM_TO("WISHLIST_ITEM_TO"),
    WISHLIST_ITEM_QUANTITY("WISHLIST_ITEM_QUANTITY"),
    
    COOKIE_HASH("COOKIE_HASH"),

    SERVICE_METHOD("SERVICE_METHOD"),

	WS_AUTH_KEY("WS_AUTH_KEY"),
	WS_CACHED_KEY("WS_CACHED_KEY"),
	WS_RESPONSE_STATUS("WS_RESPONSE_STATUS"),
	WS_RESPONSE_DESC("WS_RESPONSE_DESC"),

	MEMBER_KEY("MEMBER_KEY"),
	LOYALTY_ENGINE_MEMBER_INFO("LOYALTY_ENGINE_MEMBER_INFO"),
	LOYALTY_ENGINE_MEMBER_INFO_ENROL_OR_UPDATE("LOYALTY_ENGINE_MEMBER_INFO_ENROL_OR_UPDATE"),
	LOYALTY_ENGINE_MEMBER_BALANCE("LOYALTY_ENGINE_MEMBER_CURRENCY"),
	LOYALTY_ENGINE_MEMBER_ADDRESSES("LOYALTY_ENGINE_MEMBER_ADDRESSES"),
	LOYALTY_ENGINE_BASKET_INFO("LOYALTY_ENGINE_BASKET_INFO"),
	LOYALTY_ENGINE_QUANTITY("LOYALTY_ENGINE_QUANTITY"),
	LOYALTY_ENGINE_CURRENCY_NAME("LOYALTY_ENGINE_CURRENCY_NAME"),
	LOYALTY_ENGINE_MEMBER_INTERACTIONS("LOYALTY_ENGINE_MEMBER_INTERACTIONS"),
	LOYALTY_ENGINE_MEMBER_INTERACTIONS_PARAMS("LOYALTY_ENGINE_MEMBER_INTERACTIONS_PARAMS"),
	LOYALTY_ENGINE_MEMBER_TOKENS("LOYALTY_ENGINE_MEMBER_TOKENS"),
	LOYALTY_ENGINE_CURRENCIES("LOYALTY_ENGINE_CURRENCIES"),
	LOYALTY_ENGINE_SERVICE("LOYALTY_ENGINE_SERVICE"),

	LOYALTY_ENGINE_CONFIGURATION_TO("LOYALTY_ENGINE_CONFIGURATION_TO"),
	
	MEMBER_TO("MEMBER_TO"),
	MEMBER_AUTENTICATION_TO("MEMBER_AUTENTICATION_TO"),
	MEMBER_TO_LIST("MEMBER_TO_LIST"),
	
	MEMBER_DELIVERY_ADDRESS_TO("MEMBER_DELIVERY_ADDRESS_TO"),
	MEMBER_DELIVERY_ADDRESS_KEY("MEMBER_DELIVERY_ADDRESS_KEY"),
	MEMBER_DELIVERY_ADDRESS_TO_LIST("MEMBER_DELIVERY_ADDRESS_TO_LIST"),
	
	MEMBER_ORDER_VALIDATION("MEMBER_ORDER_VALIDATION"),
	
	MEMBER_ACCESS_TO("MEMBER_ACCESS_TO"),

	TEMPLATE_RECOVERY_EMAIL("TEMPLATE_RECOVERY_EMAIL"),
	TEMPLATE_MEMBER_ORDER_VALIDATION("TEMPLATE_MEMBER_ORDER_VALIDATION"),
	
	ADDRESS_KEY("ADDRESS_KEY"),
	ADDRESS_TEMPLATE("ADDRESS_TEMPLATE"),
	ADDRESS_TEMPLATE_TO("ADDRESS_TEMPLATE_TO"),
	ADDRESS_MAP("ADDRESS_MAP"),
	ADDRESS_NICKNAME("ADDRESS_NICKNAME"),
	
	MEMBER_TOKEN_TO("MEMBER_TOKEN_TO"),
	MEMBER_TOKEN_KEY("MEMBER_TOKEN_KEY"),
	PROGRAM_TOKEN_TYPE_TO("PROGRAM_TOKEN_TYPE_TO"),
	TOKEN_VALIDATED("TOKEN_VALIDATE"),
	TOKEN("TOKEN"),
	
	AUTHENTICATION_REQUEST_TO("AUTHENTICATION_REQUEST_TO"),
    ANNOUNCEMENT_TO("ANNOUNCEMENT_TO"),
	PAGEABLE("PAGEABLE"),
	TOTAL_PAGES("TOTAL_PAGES"),
    ANNOUNCEMENT_LIST("ANNOUNCEMENT_LIST"),
    ANNOUNCEMENT_MAP("ANNOUNCEMENT_MAP"),
    
    
    REWARD_PROVIDER_USER_PASSWORD("REWARD_PROVIDER_USER_PASSWORD"),
    REWARD_PROVIDER_USER_CODE("REWARD_PROVIDER_USER_CODE"),
    REWARD_PROVIDER_USER_TO("REWARD_PROVIDER_USER_TO"),
    
    RECOVERY_LINK_TO("RECOVERY_LINK_TO"),

    MOSAIC_CLIENT_TO("MOSAIC_CLIENT_TO"),
    PROGRAM_MOSAIC_TO("PROGRAM_MOSAIC_TO"),
    PROGRAM_MOSAIC_MODEL_TO("PROGRAM_MOSAIC_MODEL_TO"),
    PROGRAM_MOSAIC_MODEL_LIST("PROGRAM_MOSAIC_MODEL_LIST"),
    PROGRAM_MOSAIC_HIGHLIGHT_TO("PROGRAM_MOSAIC_HIGHLIGHT_TO"),
    PROGRAM_MOSAIC_HIGHLIGHT_LIST("PROGRAM_MOSAIC_HIGHLIGHT_LIST"),


    COMPRA_FACIL_PROTOCOL_TO("COMPRA_FACIL_PROTOCOL_TO"),
    
    WAITING_FOR_CONFIRMATION("WAITING_FOR_CONFIRMATION"),
    
    // LOYALTY ENGINE OAUTH
    LOYALTY_ENGINE_CONFIGURATION_MAP("LOYALTY_ENGINE_CONFIGURATION_MAP"),
    
    SUPPLIER_TRACKING_CODE_TO("SUPPLIER_TRACKING_CODE_TO"),
    
    MEMBER_MESSAGES_LIST("MEMBER_MESSAGES_LIST"),
    MEMBER_PROMOTION_TO("MEMBER_PROMOTION_TO"),
    MEMBER_TOTAL_CURRENCY_VALUE("MEMBER_TOTAL_CURRENCY_VALUE"),
    
    BUSINESS_LOGIC_OBJECT_LIST("BUSINESS_LOGIC_OBJECT_LIST"),

    ACCOUNTING_RECONCILIATION_FILE("ACCOUNTING_RECONCILIATION_FILE"),
    ACCOUNTING_RECONCILIATION_TO("ACCOUNTING_RECONCILIATION_TO"),
    WORK_BOOK_SHEET_RECONCILIATION("WORK_BOOK_SHEET_RECONCILIATION"),
    
    MEMBER_ID("MEMBER_ID"),
    
    CEP("CEP"),
    CEP_MAP("CEP_MAP"),
	CEP_CITIES_LIST("CEP_CITIES_LIST"),
	CEP_UF("CEP_UF"),
    CONFIGURATION_PROPERTIES("CONFIGURATION_PROPERTIES"),
    START_POINTS("START_POINTS"),
    FINAL_POINTS("FINAL_POINTS"),
    LIST_PRODUCT_TO("LIST_PRODUCT_TO"),
	
	FAQ_TO("FAQ_TO"),
	FAQ_TO_LIST("FAQ_TO_LIST"),
	FAQ_CATEGORY("FAQ_CATEGORY"),
	FAQ_CATEGORY_LIST("FAQ_CATEGORY"),
	CLIENT_SUPPLIER_CONFIGURATIONS_TO("CLIENT_SUPPLIER_CONFIGURATIONS_TO"),
	LIST_PRIORITY_FAQ("LIST_PRIORITY_FAQ"),
    ID_REDEMPTION_SOURCE("ID_REDEMPTION_SOURCE"),
    PLE_MEMBER_PAYLOAD("PLE_MEMBER_PAYLOAD"),

    ACCOUNT_MEMBER_PAYLOAD("ACCOUNT_MEMBER_PAYLOAD"),
    
    // TIER
    TIER_KEY("TIER_KEY"),
    TIER_LIST("TIER_LIST"),
    TIER_TO("TIER_TO"),
    
    // SALES FORCE
    INSTANCE_URL_SALES_FORCE("INSTANCE_URL_SALES_FORCE"),
    
    O_AUTH_TOKEN("O_AUTH_TOKEN"),
    PAYMENT_METHOD("PAYMENT_METHOD"),
    CURRENCY_TO_LIST("CURRENCY_TO_LIST"),
    CURRENCY_TO("CURRENCY_TO"),
    CURRENCY_KEY("CURRENCY_KEY"),
    LIST_CURRENCY_TO("LIST_CURRENCY_TO"),
    CURRENCY_MAIN("CURRENCY_MAIN"),
    CURRENCY_LIST_NOT_MAIN("CURRENCY_LIST_NOT_MAIN"),
    CURRENCY_MAP("CURRENCY_MAP"),
    MESSAGE("MESSAGE")	
    ;

    private String chave;

    private ECatalogueContextKey(final String chave) {
        this.chave = chave;
    }

    public String getChave() {
    	return chave;
    }

}

