package roteador.core.constants;

public enum MetaData
{
	// Transaction checkout info
	TOTAL_POINTS("TOTAL_POINTS"),
	MAC_ADDRESS("MAC_ADDRESS"),
	TRANSACTION_UUID("TRANSACTION_UUID"),
	
	// Business Logic
	BUSINESS_LOGIC_KEY("BUSINESS_LOGIC_KEY"),
	BUSINESS_LOGIC_SCORE("BUSINESS_LOGIC_SCORE"),
	
	MEMBER_ID("MEMBER_ID"),
	VALUE("VALUE"),

	// CPF
	CPF_NUMBER("CPF_NUMBER"),

	// ADDRESS
	ADDRESS_LAST_CHANGE_DATE("ADDRESS_LAST_CHANGE_DATE"),
	ADDRESS_CHANGE_TIMES("ADDRESS_CHANGE_TIMES"),
	
	ADDRESS_ZIPCODE("ADDRESS_ZIPCODE"),
	ADDRESS_NUMBER("ADDRESS_NUMBER"),
	ADDRESS_CITY("ADDRESS_CITY"),
	ADDRESS_DISTRICT("ADDRESS_DISTRICT"),
	ADDRESS_ADDRESS_LINE("ADDRESS_ADDRESS_LINE"),
	ADDRESS_ADDRESS_LINE_OPTIONAL("ADDRESS_ADDRESS_LINE_OPTIONAL"),
	ADDRESS_REFERENCE_POINT("ADDRESS_REFERENCE_POINT"),
	ADDRESS_STATE("ADDRESS_STATE"),
	ADDRESS_TYPE("ADDRESS_TYPE"),
	ADDRESS_CHANGE_DATE("ADDRESS_CHANGE_DATE"),

	;

	private String chave;

	public String getChave()
	{
		return chave;
	}

	private MetaData(String chave)
	{
		this.chave = chave;
	}
}
